name: tezster_wallet
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bs58check: ^1.0.1
  clay_containers: 0.2.3
  cupertino_icons: ^1.0.2
  firebase_core: ^1.10.0
  firebase_crashlytics: 2.3.0
  flutter:
    sdk: flutter
  flutter_file_path_provider: ^0.0.3
  flutter_inappwebview: 5.3.1
  flutter_secure_storage: ^4.2.0
  flutter_svg: ^0.22.0
  fluttertoast: ^8.0.3
  get: 4.1.4
  intl: ^0.17.0
  local_auth: ^1.1.3
  majascan: ^0.4.0
  permission_handler: ^6.1.1
  pinput: 1.0.0
  qr_flutter: 4.0.0
  share: ^2.0.1
  simple_gql: ^1.2.0
  tezster_dart:
    git:
      url: https://github.com/Jay-Tezsure/Tezster_dart.git
      ref: gasFeeCal
  uni_links: ^0.5.1
  url_launcher: ^6.0.6
  video_player: ^2.2.3
  firebase_analytics: ^8.3.4
  shimmer: ^2.0.0
  share_plus: 2.0.0

dependency_overrides:
  firebase_crashlytics_platform_interface: 3.1.13

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/login/
    - assets/icon/
    - assets/home/
    - assets/wallet/
    - assets/tran_history/
    - assets/walkthrough/
    - assets/success_page/
    - assets/recovery_phrase/
    - assets/send_xtz/
    - assets/receiveFunds/
    - assets/settings/
    - assets/emojis/
    - assets/multiple_account/
    - assets/import_account/
    - assets/nft/

  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato-Regular.ttf
    - family: Poppins
      fonts:
        - asset: fonts/poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/poppins/Poppins-Medium.ttf
          weight: 500
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 700
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bol  d.ttf
  #
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
